<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Compilers" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpCodingAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CommandLine\CommandConfirmAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CommandLine\CommandExecuteAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpDesignForComplexConsoleAgent.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpDesignForComplexWPFAgent.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpDesignForMultiViewWPFAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpDesignForSimpleConsoleAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpDesignForSimpleWPFAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpRequirementAnalysisAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\ReactTypeScript\ReactTypeScriptCodingAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\ReactTypeScript\ReactTypeScriptCodingTaskCreateAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\ReactTypeScript\ReactTypeScriptDesignForSPAAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\ReactTypeScript\ReactTypeScriptRequirementAnalysisAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Review\ReviewConfirmAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Review\ReviewHandleAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\CSharp\CSharpCodingTaskCreateAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Role\RoleCreationManagerAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Role\RoleCreatorAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Role\RolePlannerAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Requirement\RequirementRoutingAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Requirement\RequirementAnalysisSchedulingAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Agents\Requirement\RequirementHandleTaskManagerAgent.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\EmailSender\EmailSender.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\EmailSender\mail_config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\EmailSender\README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\JsonFormatter\JsonFormatter.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\JsonFormatter\JsonFormatter.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\JsonFormatter\JsonFormatter.runtimeconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\JsonFormatter\README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\D3DCompiler_47_cor3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\PenImc_cor3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\PresentationNative_cor3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\ScreenshotTool.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\vcruntime140_cor3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ScreenshotTool\wpfgfx_cor3.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ShiftJisToUtf8Converter\README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ShiftJisToUtf8Converter\ShiftJisToUtf8Converter.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Configs\Tools\ToolsConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configs\ToolCalls\" />
  </ItemGroup>

</Project>
